### ISSUE TITLE
Npm test watch error

### ISSUE THREAD

**Issue by Cst2989** [phacks/redux-todomvc#1]
This is the error:

 redux-tomomvc@1.0.0 test:watch C:\xampp\htdocs\redux-tomomvc

> npm run test -- --watch --watch-extensions jsx
> 
> redux-tomomvc@1.0.0 test C:\xampp\htdocs\redux-tomomvc
> mocha --compilers js:babel-core/register --require ./test/setup.js 'test/*_/_.@(js|jsx)' "--watch" "--watch-extensions" "jsx"

'jsx)'' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "test" "--" "--watch" "--watch-extensions" "jsx"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! redux-tomomvc@1.0.0 test: `mocha --compilers js:babel-core/register --require ./test/setup.js 'test/**/*.@(js|jsx)' "--watch" "--watch-extensions" "jsx"`
npm ERR! Exit status 255
npm ERR!

I use Windows btw.

**Comment by phacks** [comment]
Hello ! Thanks for reporting the error. It seems that it is related to the way Windows handles some symbols in the command. Although I don't have a Windows machine at hand right now, could you try replacing the faulty line with the following?

``` bash
"mocha --compilers js:babel-core/register --require ./test/setup.js test/**/*.jsx"
```

**Comment by Cst2989** [comment]
Seems to work now. No more errors

**Comment by vu1n** [comment]
I was able to resolve this by replacing the single quotes in the original command with an escaped double quote.

`"mocha --compilers js:babel-core/register --require ./test/setup.js \"test/**/*.@(js|jsx)\""`
