### ISSUE TITLE
Webpack dev server not working

### ISSUE THREAD

**Issue by teekaay** [phacks/redux-todomvc#2]
Hey,
I recently read your article (great, btw) and decided to get my hands dirty while following your article. When I do the webpack configuration part (with dev server) and run `webpack-dev-server` there is no web page on `localhost:8080` as described. I also cloned your repo and tried it, but no success. 
Maybe you could give more hints on how to get the dev server running?

**Comment by agad** [comment]
+1.  Same problem.  If I try to run the dev server with the simple webpage-dev-server command, I get:

```
http://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from ./dist
Hash: d3bba4c38958f38da4ad
Version: webpack 1.12.14
Time: 9352ms
```

After all the files are built and included, I get:

`webpack: bundle is now VALID.`

But any attempt to get to **http://localhost:8080/webpack-dev-server/** results in the browser being unable to make a connection to the server.

**Comment by phacks** [comment]
@agad Have you tried connecting on `http://localhost:8080` only? I get the same output from the `webpack-dev-server` command, so nothing seems to go wrong when running it.

@teekaay Could you give me the output of the `webpack-dev-server` command please? Or is it the same as @agad?

**Comment by agad** [comment]
Ah hitting  http://localhost:8080 solves the problem.  Doh.

On Mon, Apr 4, 2016 at 11:36 AM, Nicolas Goutay notifications@github.com
wrote:

> @agad https://github.com/agad Have you tried connecting on
> http://localhost:8080 only? I get the same output from the
> webpack-dev-server command, so nothing seems to go wrong when running it.
> 
> @teekaay https://github.com/teekaay Could you give me the output of the
> webpack-dev-server command please? Or is it the same as @agad
> https://github.com/agad?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/phacks/redux-todomvc/issues/2#issuecomment-205354392

## 

# 

Alex Gadea - President - Leaf Level Labs, Inc. | www.leaflevellabs.com

**Comment by phacks** [comment]
@agad Glad to hear it!

**Comment by phacks** [comment]
Closing this issue, problem seems to be resolved.
