### ISSUE TITLE
directory layout not present after `npm init -y`

### ISSUE THREAD

**Issue by rsyring** [phacks/redux-todomvc#4]
At the beginning of part 1 of the tutorial, it says:

> The project directory will look like the following:

```
├── dist
│   ├── bundle.js
│   └── index.html
├── node_modules
├── package.json
├── src
├── test
└── webpack.config.js
```

But using npm 2.15.1, I only get a package.json file.  No other folders or files in the directory.

**Comment by phacks** [comment]
Oh yes, I should have made this more obvious: the command `npm init -y` only creates the `package.json` file with default settings, without asking for user input at each step (`yes` or `no`). The directory will look like this at the end of the tutorial, the other files or directories (except `node_modules`, which is a result of `npm install`) will be coded by hand.
