### ISSUE TITLE
JS comment in JSX shows up in 

### ISSUE THREAD

**Issue by rsyring** [phacks/redux-todomvc#5]
You have the snippet:

``` jsx
      </div>
      <TextInput /> // We add the TextInput component
    </li>
```

That JS comment after the `<TextInput />` ends up being in the output of the page for me.

![text-input-comment](https://cloud.githubusercontent.com/assets/109467/14830412/90df3a08-0bbe-11e6-9f94-a65254d8e84a.png)

**Comment by phacks** [comment]
The comments have been removed in the last commits, thanks for pointing that out!
